"""Quiz question bank (English).

Each question: text, 4 options, the index (0..3) of the correct answer, and a
category. Question pool is shuffled fresh each game and drawn sequentially, so
no question repeats within a single game.
"""

from __future__ import annotations

# (question, [a, b, c, d], correct_index, category)
_RAW: list[tuple[str, list[str], int, str]] = [
    ("What is the capital of Poland?", ["Kraków", "Warsaw", "Gdańsk", "Poznań"], 1, "Geography"),
    ("How many continents are there on Earth?", ["5", "6", "7", "8"], 2, "Geography"),
    ("The longest river in Europe is the:", ["Vistula", "Danube", "Volga", "Dnieper"], 2, "Geography"),
    ("The capital of France is:", ["Lyon", "Marseille", "Paris", "Nice"], 2, "Geography"),
    ("Which ocean is the largest?", ["Atlantic", "Pacific", "Indian", "Arctic"], 1, "Geography"),
    ("The highest mountain in the world is:", ["K2", "Kilimanjaro", "Mount Everest", "Mont Blanc"], 2, "Geography"),
    ("The capital of Japan is:", ["Osaka", "Tokyo", "Kyoto", "Hiroshima"], 1, "Geography"),
    ("Paris is in which country?", ["Germany", "Italy", "France", "Spain"], 2, "Geography"),
    ("What is the largest island in the world?", ["Madagascar", "Greenland", "Borneo", "Iceland"], 1, "Geography"),
    ("The capital of Italy is:", ["Milan", "Turin", "Naples", "Rome"], 3, "Geography"),
    ("The smallest continent is:", ["Europe", "Australia", "Antarctica", "South America"], 1, "Geography"),
    ("Which country borders the Baltic Sea?", ["Switzerland", "Poland", "Austria", "Czech Republic"], 1, "Geography"),
    ("The Amazon flows through:", ["Brazil", "Egypt", "China", "India"], 0, "Geography"),
    ("Lake Baikal is in which country?", ["Poland", "Russia", "Canada", "Mongolia"], 1, "Geography"),
    ("The capital of Spain is:", ["Barcelona", "Seville", "Madrid", "Valencia"], 2, "Geography"),
    ("The Sahara Desert is in:", ["North America", "Africa", "Asia", "Oceania"], 1, "Geography"),
    ("Which country does NOT border Poland?", ["Ukraine", "Lithuania", "Slovakia", "Romania"], 3, "Geography"),
    ("The largest lake in Poland is:", ["Jeziorak", "Śniardwy", "Mamry", "Łebsko"], 1, "Geography"),
    ("The capital of Germany is:", ["Munich", "Hamburg", "Berlin", "Cologne"], 2, "Geography"),
    ("Which country is called the land of a thousand lakes?", ["Sweden", "Finland", "Norway", "Denmark"], 1, "Geography"),
    ("The capital of the United States is:", ["New York", "Los Angeles", "Washington, D.C.", "Chicago"], 2, "Geography"),
    ("Which country is the largest by area?", ["China", "Canada", "Russia", "USA"], 2, "Geography"),
    ("On which continent is Egypt?", ["Asia", "Europe", "Africa", "Oceania"], 2, "Geography"),
    ("Which sea does the Vistula flow into?", ["Baltic", "Black", "North", "Mediterranean"], 0, "Geography"),
    ("The capital of Portugal is:", ["Porto", "Lisbon", "Madrid", "Barcelona"], 1, "Geography"),
    ("In which year did the Warsaw Uprising begin?", ["1939", "1943", "1944", "1945"], 2, "History"),
    ("The baptism of Poland is dated to the year:", ["966", "1000", "996", "1025"], 0, "History"),
    ("Who was the first historical ruler of Poland?", ["Bolesław Chrobry", "Mieszko I", "Casimir the Restorer", "Casimir the Great"], 1, "History"),
    ("In which year did Poland regain independence?", ["1918", "1920", "1939", "1945"], 0, "History"),
    ("The Battle of Grunwald took place in:", ["1410", "1454", "1386", "1466"], 0, "History"),
    ("Who commanded the Polish-Lithuanian forces at Grunwald?", ["Casimir the Great", "Władysław Jagiełło", "Bolesław Chrobry", "John III Sobieski"], 1, "History"),
    ("The Union of Lublin was signed in:", ["1569", "1587", "1492", "1605"], 0, "History"),
    ("The Constitution of 3 May was adopted in:", ["1791", "1793", "1795", "1792"], 0, "History"),
    ("King John III Sobieski won the Battle of Vienna in:", ["1680", "1683", "1690", "1673"], 1, "History"),
    ("The first historical capital of Poland was:", ["Kraków", "Warsaw", "Gniezno", "Poznań"], 2, "History"),
    ("World War II began in:", ["1938", "1939", "1940", "1945"], 1, "History"),
    ("In which year did the Third Partition remove Poland from the map?", ["1772", "1793", "1795", "1807"], 2, "History"),
    ("Who was the first president of Poland after 1989?", ["Lech Wałęsa", "Wojciech Jaruzelski", "Aleksander Kwaśniewski", "Bronisław Komorowski"], 0, "History"),
    ("Which king founded the Academy of Kraków?", ["Casimir the Great", "Władysław Jagiełło", "Sigismund Augustus", "John I Albert"], 0, "History"),
    ("Who wrote the Polish national anthem?", ["Józef Wybicki", "Adam Mickiewicz", "Juliusz Słowacki", "Wojciech Bogusławski"], 0, "History"),
    ("In which year did Poland join the European Union?", ["2002", "2004", "2007", "2011"], 1, "History"),
    ("What is associated with the year 1410?", ["baptism of Poland", "Battle of Grunwald", "feudal fragmentation", "Constitution of 3 May"], 1, "History"),
    ("Who wrote \"Pan Tadeusz\"?", ["Juliusz Słowacki", "Adam Mickiewicz", "Henryk Sienkiewicz", "Bolesław Prus"], 1, "Literature"),
    ("The author of \"The Doll\" (Lalka) is:", ["Bolesław Prus", "Eliza Orzeszkowa", "Maria Konopnicka", "Juliusz Słowacki"], 0, "Literature"),
    ("Who wrote the novel \"Quo Vadis\"?", ["Henryk Sienkiewicz", "Adam Mickiewicz", "Cyprian Norwid", "Jan Kochanowski"], 0, "Literature"),
    ("Who wrote the drama \"Dziady\" (Forefathers' Eve)?", ["Adam Mickiewicz", "Juliusz Słowacki", "Zygmunt Krasiński", "Henryk Sienkiewicz"], 0, "Literature"),
    ("The author of \"Koziołek Matołek\" is:", ["Kornel Makuszyński", "Jan Brzechwa", "Julian Tuwim", "Maria Konopnicka"], 0, "Literature"),
    ("Who wrote the poem \"Lokomotywa\"?", ["Julian Tuwim", "Jan Brzechwa", "Marian Hemar", "Tadeusz Różewicz"], 0, "Literature"),
    ("Who wrote the novel \"The Knights of the Cross\"?", ["Henryk Sienkiewicz", "Bolesław Prus", "Eliza Orzeszkowa", "Władysław Reymont"], 0, "Literature"),
    ("A Polish Nobel laureate in literature (2018) is:", ["Olga Tokarczuk", "Wisława Szymborska", "Maria Dąbrowska", "Eliza Orzeszkowa"], 0, "Literature"),
    ("Which poet won the 1980 Nobel Prize in Literature?", ["Czesław Miłosz", "Wisława Szymborska", "Zbigniew Herbert", "Adam Zagajewski"], 0, "Literature"),
    ("Who wrote the comedy \"Zemsta\" (The Revenge)?", ["Aleksander Fredro", "Juliusz Słowacki", "Adam Mickiewicz", "Stanisław Wyspiański"], 0, "Literature"),
    ("The author of the drama \"Wesele\" (The Wedding) is:", ["Stanisław Wyspiański", "Józef Szujski", "Władysław Reymont", "Tadeusz Boy-Żeleński"], 0, "Literature"),
    ("Who wrote \"Balladyna\"?", ["Juliusz Słowacki", "Adam Mickiewicz", "Zygmunt Krasiński", "Jan Kochanowski"], 0, "Literature"),
    ("Jan Kochanowski was a prominent poet of the:", ["Renaissance", "Romantic era", "Positivist era", "Modernist era"], 0, "Literature"),
    ("The author of \"Syzyfowe prace\" is:", ["Stefan Żeromski", "Bolesław Prus", "Henryk Sienkiewicz", "Maria Konopnicka"], 0, "Literature"),
    ("Who wrote \"The Deluge\" (Potop)?", ["Henryk Sienkiewicz", "Bolesław Prus", "Stefan Żeromski", "Władysław Reymont"], 0, "Literature"),
    ("The 1924 Nobel laureate who wrote \"The Peasants\" is:", ["Władysław Reymont", "Henryk Sienkiewicz", "Czesław Miłosz", "Olga Tokarczuk"], 0, "Literature"),
    ("H₂O is the chemical formula for:", ["oxygen", "water", "hydrogen peroxide", "hydroxide"], 1, "Science"),
    ("The chemical symbol for gold is:", ["Au", "Ag", "Fe", "Ai"], 0, "Science"),
    ("Who formulated the theory of relativity?", ["Isaac Newton", "Albert Einstein", "Nicolaus Copernicus", "Marie Curie"], 1, "Science"),
    ("The planet closest to the Sun is:", ["Venus", "Earth", "Mercury", "Mars"], 2, "Science"),
    ("The largest planet in the Solar System is:", ["Saturn", "Jupiter", "Neptune", "Uranus"], 1, "Science"),
    ("The value of π is approximately:", ["3.14", "2.72", "1.62", "3.41"], 0, "Science"),
    ("The unit of electric current is the:", ["volt", "ampere", "ohm", "watt"], 1, "Science"),
    ("The chemical symbol for sodium is:", ["So", "S", "Na", "Sn"], 2, "Science"),
    ("Sodium chloride (NaCl) is commonly known as:", ["table salt", "sugar", "soda", "hydrochloric acid"], 0, "Science"),
    ("The celestial body orbiting the Earth is the:", ["Sun", "Moon", "Mars", "Venus"], 1, "Science"),
    ("The main component of air is:", ["oxygen", "carbon dioxide", "nitrogen", "hydrogen"], 2, "Science"),
    ("The acid found in stomach juice is:", ["sulfuric acid", "hydrochloric acid", "nitric acid", "acetic acid"], 1, "Science"),
    ("The chemical formula for carbon dioxide is:", ["CO", "CO₂", "O₂", "CH₄"], 1, "Science"),
    ("How many minutes are there in an hour?", ["30", "60", "100", "90"], 1, "Science"),
    ("How many hours are there in a day?", ["12", "24", "8", "48"], 1, "Science"),
    ("What is 7 × 8?", ["54", "56", "58", "63"], 1, "Science"),
    ("What is 9 × 9?", ["81", "72", "99", "64"], 0, "Science"),
    ("What is 12 × 12?", ["24", "120", "144", "132"], 2, "Science"),
    ("How many days are there in a leap year?", ["365", "364", "366", "367"], 2, "Science"),
    ("How many months are there in a year?", ["10", "11", "12", "13"], 2, "Science"),
    ("What is 5 squared (5²)?", ["10", "25", "15", "32"], 1, "Science"),
    ("How many bones are there in an adult human body?", ["206", "306", "106", "156"], 0, "Science"),
    ("Water freezes at (in degrees Celsius):", ["0", "100", "4", "-10"], 0, "Science"),
    ("How many seconds are there in a minute?", ["30", "60", "100", "90"], 1, "Science"),
    ("DNA stands for:", ["deoxyribonucleic acid", "ribonucleic acid", "deoxyglucose", "deoxyribose"], 0, "Science"),
    ("The main processor of a computer is the:", ["GPU", "CPU", "RAM", "SSD"], 1, "Technology"),
    ("One kilobyte (KB) is approximately:", ["1000 bytes", "10 bytes", "100 bytes", "1,000,000 bytes"], 0, "Technology"),
    ("The abbreviation \"WWW\" stands for:", ["World Wide Web", "Web Wide World", "Welcome Web World", "World Web Wide"], 0, "Technology"),
    ("A co-founder of Microsoft is:", ["Bill Gates", "Steve Jobs", "Mark Zuckerberg", "Jeff Bezos"], 0, "Technology"),
    ("A co-founder of Apple is:", ["Bill Gates", "Steve Jobs", "Elon Musk", "Larry Page"], 1, "Technology"),
    ("Who composed the opera \"Halka\"?", ["Stanisław Moniuszko", "Frédéric Chopin", "Ignacy Paderewski", "Henryk Wieniawski"], 0, "Music"),
    ("The composer of \"The Four Seasons\" violin concertos is:", ["Antonio Vivaldi", "Johann Sebastian Bach", "Ludwig van Beethoven", "Wolfgang Amadeus Mozart"], 0, "Music"),
    ("The Polish composer of the \"Revolutionary Étude\" is:", ["Stanisław Moniuszko", "Frédéric Chopin", "Karol Szymanowski", "Ignacy Paderewski"], 1, "Music"),
    ("The singer of the band Maanam (\"Szklana pogoda\") is:", ["Kora", "Maryla Rodowicz", "Edyta Górniak", "Beata Kozidrak"], 0, "Music"),
    ("The rock band \"Perfect\" became popular in the:", ["1970s", "1980s", "1990s", "1960s"], 1, "Music"),
    ("The singer of the band Bajm is:", ["Beata Kozidrak", "Kora", "Urszula", "Kayah"], 0, "Music"),
    ("The Polish history painter who painted the \"Battle of Grunwald\" is:", ["Jan Matejko", "Piotr Michałowski", "Wojciech Kossak", "Jan Styka"], 0, "Art"),
    ("Leonardo da Vinci's \"Lady with an Ermine\" is in a museum in:", ["Paris", "Kraków", "London", "Vienna"], 1, "Art"),
    ("Who painted the \"Mona Lisa\"?", ["Michelangelo", "Leonardo da Vinci", "Raphael", "Caravaggio"], 1, "Art"),
    ("The author of \"The Scream\" (Norwegian painter) is:", ["Edvard Munch", "Pablo Picasso", "Claude Monet", "Vincent van Gogh"], 0, "Art"),
    ("Who painted the series of paintings with sunflowers?", ["Vincent van Gogh", "Claude Monet", "Paul Cézanne", "Pierre Renoir"], 0, "Art"),
    ("Wawel Castle is located in:", ["Warsaw", "Poznań", "Kraków", "Gdańsk"], 2, "Art"),
    ("How many lives does each player start with in \"One in Ten\"?", ["1", "2", "3", "10"], 2, "Games"),
    ("In which country was the band The Beatles formed?", ["United Kingdom", "USA", "Germany", "Ireland"], 0, "Music"),
    ("How many players can play \"Quiz\" (maximum)?", ["2", "5", "10", "20"], 2, "Games"),
]

def _to_q(text: str, options: list[str], answer: int, category: str) -> dict:
    return {"text": text, "options": options, "answer": answer, "category": category}


QUESTIONS = [_to_q(q, opts, ans, cat) for q, opts, ans, cat in _RAW]
